src/django_secret_sharing/urls.py
from django.urls import include, path

from django_secret_sharing import views

app_name = "django_secret_sharing"


urlpatterns = [
    path("", views.CreateSecretView.as_view(), name="create"),
    path(
        "generate-password/",
        views.GeneratePasswordView.as_view(),
        name="generate-password",
    ),
    path("<str:url_part>/", views.RetreiveSecretView.as_view(), name="retrieve"),
    path("<str:url_part>/view/", views.ViewSecretView.as_view(), name="view"),
]

src/django_secret_sharing/models.py
import os
import uuid

from django.conf import settings
from django.db import models
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _


class MutationDateModel(models.Model):
    created_at = models.DateTimeField(
        _("created at"), auto_now_add=True, editable=False
    )
    modified_at = models.DateTimeField(_("modified at"), auto_now=True, editable=False)

    class Meta:
        abstract = True


class ExpiryModel(models.Model):
    expires_in = models.IntegerField(blank=False, null=True)

    class Meta:
        abstract = True


class SecretManager(models.Manager):
    def get_non_erased(self):
        return self.filter(erased=False)


class AbstractSecret(ExpiryModel, MutationDateModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    value = models.BinaryField(blank=True, null=True)
    erased = models.BooleanField(default=False)
    view_once = models.BooleanField(default=True)
    expires_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    erased_at = models.DateTimeField(blank=True, null=True)

    objects = SecretManager()

    def erase(self, *args, **kwargs):
        self.value = None
        self.erased = True
        self.expires_at = None
        self.erased_at = timezone.now()
        self.save()

    def has_expired(self):
        if self.erased:
            return True
        if self.expires_at:
            return timezone.now() > self.expires_at
        return False

    class Meta:
        abstract = True
        verbose_name = _("Secret")
        verbose_name_plural = _("Secrets")


class Secret(AbstractSecret):
    pass


class FileManager(models.Manager):
    pass


class AbstractFile(ExpiryModel, MutationDateModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    secret = models.ForeignKey(
        "django_secret_sharing.Secret",
        related_name="files",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    ref = models.TextField(unique=True)

    objects = FileManager()

    class Meta:
        abstract = True
        verbose_name = _("File")
        verbose_name_plural = _("Files")


class File(AbstractFile):
    @cached_property
    def filename(self):
        head, tail = os.path.split(self.ref)
        return tail

    @cached_property
    def download_url(self):
        from django_secret_sharing.utils import get_backend

        backend = get_backend()
        return backend.get_download_url(self)

src/django_secret_sharing/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from django_secret_sharing import settings
from django_secret_sharing.models import File
from django_secret_sharing.utils import get_backend


class CreateSecretForm(forms.Form):
    expires = forms.TypedChoiceField(
        label=_("Expires in"), choices=settings.EXPIRY_TIME_CHOICES, coerce=int
    )
    view_once = forms.BooleanField(
        label=_("View once"),
        help_text=_(
            "When checked the message will only be able to be viewed once and then disappears forever"
        ),
        widget=forms.CheckboxInput(attrs={"checked": "checked"}),
        required=False,
    )
    value = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={"placeholder": _("Secret content here")}),
    )
    file_refs = forms.CharField(
        required=False,
        widget=forms.HiddenInput(),
    )

    def clean_file_refs(self):
        file_refs = self.cleaned_data["file_refs"]
        file_refs = (
            self.cleaned_data["file_refs"].split(",") if file_refs is not "" else []
        )

        if File.objects.filter(ref__in=file_refs).exists():
            raise ValidationError(_("File(s) already exists"))

        backend = get_backend()

        if not backend.validate_file_refs(file_refs):
            raise ValidationError(_("File(s) not uploaded"))

        return file_refs

src/django_secret_sharing/views.py
from django.http import Http404
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from django_secret_sharing import settings
from django_secret_sharing.exceptions import SecretNotFound
from django_secret_sharing.forms import CreateSecretForm
from django_secret_sharing.utils import create_secret, get_secret_by_url_part


@method_decorator(never_cache, name="dispatch")
@method_decorator(sensitive_post_parameters("value"), name="dispatch")
class CreateSecretView(generic.FormView):
    template_name = "django_secret_sharing/create.html"
    form_class = CreateSecretForm

    def get_success_url(self):
        return reverse("django_secret_sharing:create")

    def form_valid(self, form):
        secret, url_part = create_secret(
            value=form.cleaned_data.get("value"),
            expires_in=form.cleaned_data.get("expires"),
            view_once=form.cleaned_data.get("view_once"),
            file_refs=form.cleaned_data["file_refs"],
        )

        context = super().get_context_data()
        context["secret"] = secret
        context["secret_url"] = self.request.build_absolute_uri(
            reverse("django_secret_sharing:retrieve", kwargs={"url_part": url_part})
        )
        return self.render_to_response(context)


@method_decorator(never_cache, name="dispatch")
class RetreiveSecretView(generic.TemplateView):
    template_name = "django_secret_sharing/retrieve.html"

    def get_context_data(self, **kwargs):
        url_part = kwargs["url_part"]

        try:
            secret, value = get_secret_by_url_part(url_part)
        except (SecretNotFound, ValueError):
            raise Http404()

        context = super().get_context_data(**kwargs)
        context["secret"] = secret
        context["url_part"] = url_part
        return context


@method_decorator(never_cache, name="dispatch")
class ViewSecretView(generic.TemplateView):
    template_name = "django_secret_sharing/view.html"

    def get_context_data(self, **kwargs):
        url_part = kwargs["url_part"]

        try:
            secret, value = get_secret_by_url_part(url_part)
        except SecretNotFound:
            raise Http404()

        if secret.view_once:
            secret.erase()

        context = super().get_context_data(**kwargs)
        context["secret"] = secret
        context["value"] = value
        return context


class GeneratePasswordView(CreateSecretView):
    def get_initial(self):
        initial = super().get_initial()
        initial["value"] = get_random_string(settings.PASSWORD_LENGTH)
        return initial

src/django_secret_sharing/templates/django_secret_sharing/create.html
{% if secret_url %}
    <p>{{ secret_url }}</p>
    <a href="{% url 'django_secret_sharing:create' %}">Create</a>
{% else %}
  <form id="secret_form" action="{% url 'django_secret_sharing:create' %}" method="post" novalidate>
      {% csrf_token %}
      {{ form }}
      <div id="files"></div>
      <button type="button" id="add_file">Add file</button>
      <input type="submit" value="Submit">
      <a href="{% url 'django_secret_sharing:generate-password' %}">Generate password</a>
  </form>
{% endif %}

{% block scripts %}
{% include "django_secret_sharing/file_transfer_simple.html" %}
{% include "django_secret_sharing/file_transfer_scripts.html" %}
{% endblock %}

src/django_secret_sharing/templates/django_secret_sharing/file_transfer_scripts.html
<script type="text/javascript">
    (function(root) {
        var uploadFileUrl = '{% url "django_secret_sharing_api:upload-file-url" %}';

        function getUploadFileUrl(filename, expiresIn) {
            return new Promise(function(resolve, reject) {
                fetch(uploadFileUrl, {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        filename: filename,
                        expires_in: expiresIn
                    })
                }).then(function(res) {
                    res.json().then(resolve).catch(reject);
                }).catch(reject);    
            });
        }

        function uploadFile(file, expiresIn) {
            return new Promise(function(resolve, reject) {
                getUploadFileUrl(file.name, expiresIn).then(function(data) {
                    var formData = new FormData();

                    Object.entries(data.fields).forEach(([key, value]) => {
                        formData.append(key, value);
                    });

                    formData.append('file', file);

                    fetch(data.url, {
                        method: 'POST',
                        body: formData,
                        credentials: 'include'
                    }).then(function(res) {
                        if (res && res.ok) {
                            if (root.handleSecretFileUploaded) {
                                root.handleSecretFileUploaded.apply(null, [data.fields.key, file]);
                            }
                        }

                        resolve(res);
                    }).catch(reject);
                }).catch(reject);
            });
        }

        root.uploadFile = uploadFile;
    })(this);
</script>

src/django_secret_sharing/templates/django_secret_sharing/file_transfer_simple.html
<script type="text/javascript">
    (function(root) {
      var form = document.getElementById('secret_form');
  
      if (!form) {
        return;
      }
  
      var filesEl = document.getElementById('files');
      var addFileEl = document.getElementById('add_file');
      var fileRefsEl = document.getElementById('id_file_refs');
      var expiresEl = document.getElementById('id_expires');
      var addFileInputs = [];
  
      // Set file_refs value
      root.handleSecretFileUploaded = function(fileRef, file) {
        fileRefsEl.value = fileRefsEl.value.split(",").concat(fileRef).join(",")
      };

      if (addFileEl) {
        addFileEl.addEventListener('click', function() {
          var input = document.createElement('input');
          input.type = 'file';
  
          addFileInputs.push(input);
  
          filesEl.appendChild(input);
        });
      }
  
      function handleFormSubmit(event) {
        if (addFileInputs.length) {
          var files = [];
  
          addFileInputs.forEach(function(el) {
            if (el.files.length) {
              for (var i = 0; i < el.files.length; i++) {
                files.push(el.files.item(i));
              }
            }
          });
        }
  
        if (files.length) {
          event.preventDefault();
  
          var expiresIn = parseInt(expiresEl.value);
          var uploadFilePromises = []
  
          files.forEach(function(file) {
            uploadFilePromises.push(uploadFile(file, expiresIn));
          });
  
          Promise.all(uploadFilePromises).then(function(values) {
            // Remove submit handler for file uploads and submit form values with file_refs
            form.removeEventListener('submit', handleFormSubmit);
            form.submit();
          }).catch(function() {
            alert('Something went wrong during the file upload, please try again.')
          });
  
          return false;
        }
      }
  
      form.addEventListener('submit', handleFormSubmit);
    })(this);
  </script>

src/django_secret_sharing/templates/django_secret_sharing/retrieve.html
<a href="{% url 'django_secret_sharing:view' url_part %}">View</a>

src/django_secret_sharing/templates/django_secret_sharing/view.html
<textarea disabled>{{ value }}</textarea>
{% if secret.files.all %}
<ul>
    {% for file in secret.files.all %}
    <li>
        <a href="{{ file.download_url }}" target="_blank" ref="noopener noreferrer">{{ file.filename }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'django_secret_sharing:create' %}">Create</a>